pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:tadinhdong/docker-compose.git
          - cd docker-compose.git
          - git push --mirror git@github.com:zero0608/docker-compose.git